version: "3.3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: rain_sensor
    volumes:
      - .:/app
    environment:
      RS_SERVER_URL: ${RS_SERVER_URL:-:8080}
      RS_ENVIRONMENT: ${RS_ENVIRONMENT:-development}
    ports:
      - "8082:8080"
  builder:
    build:
      context: .
    container_name: rain_sensor_builder
    volumes:
      - .:/app
