version: "3.3"

services:
  rain_sensor:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: rain_sensor
    networks:
      - water-system
    volumes:
      - .:/app
    environment:
      RS_SERVER_URL: ${RS_SERVER_URL:-:8080}
      RS_ENVIRONMENT: ${RS_ENVIRONMENT:-development}
    ports:
      - "8082:8080"
networks:
  water-system:
    external: true