// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rs_test

import (
	"github.com/bruli/raspberryRainSensor/pkg/rs"
	http2 "net/http"
	"sync"
)

// Ensure, that HTTPClientMock does implement rs.HTTPClient.
// If this is not the case, regenerate this file with moq.
var _ rs.HTTPClient = &HTTPClientMock{}

// HTTPClientMock is a mock implementation of rs.HTTPClient.
//
//	func TestSomethingThatUsesHTTPClient(t *testing.T) {
//
//		// make and configure a mocked rs.HTTPClient
//		mockedHTTPClient := &HTTPClientMock{
//			DoFunc: func(req *http2.Request) (*http2.Response, error) {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedHTTPClient in code that requires rs.HTTPClient
//		// and then make assertions.
//
//	}
type HTTPClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(req *http2.Request) (*http2.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Req is the req argument value.
			Req *http2.Request
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *HTTPClientMock) Do(req *http2.Request) (*http2.Response, error) {
	if mock.DoFunc == nil {
		panic("HTTPClientMock.DoFunc: method is nil but HTTPClient.Do was just called")
	}
	callInfo := struct {
		Req *http2.Request
	}{
		Req: req,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(req)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedHTTPClient.DoCalls())
func (mock *HTTPClientMock) DoCalls() []struct {
	Req *http2.Request
} {
	var calls []struct {
		Req *http2.Request
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
